name: Tests

on:
  workflow_dispatch:
  push:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -e '.[dev]'

    - name: Check formatting with Ruff
      run: |
        source .venv/bin/activate
        ruff format --check .

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest tests/ -v --cov=ipychat
